
# autogenerated from @sddc_guy codegen
    

Function Get-HABuuid

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function uuid
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABchannel_types

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function channel-types
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABconfig_descriptions

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function config-descriptions
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABbindings

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function bindings
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABservices

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function services
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABdiscovery

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function discovery
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABpersistence

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function persistence
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABthing_types

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function thing-types
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABitems

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function items
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABinbox

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function inbox
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABlinks

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function links
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABthings

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function things
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABsitemaps

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function sitemaps
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABiconsets

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function iconsets
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABextensions

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function extensions
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habmincharts

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/charts
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habmindashboards

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/dashboards
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habmindesigner

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/designer
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habminfloorplan

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/floorplan
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habminrules

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/rules
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABtemplates

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function templates
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABmodule_types

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function module-types
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABrules

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function rules
    $MySelf
    }

