
# autogenerated from @sddc_guy codegen
    

Function Get-HABuuid

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function uuid -Object_Type HABuuid
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABchannel_types

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function channel-types -Object_Type HABchannel_types
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABconfig_descriptions

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function config-descriptions -Object_Type HABconfig_descriptions
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABbindings

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function bindings -Object_Type HABbindings
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABservices

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function services -Object_Type HABservices
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABdiscovery

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function discovery -Object_Type HABdiscovery
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABpersistence

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function persistence -Object_Type HABpersistence
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABthing_types

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function thing-types -Object_Type HABthing_types
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABitems

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function items -Object_Type HABitems
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABinbox

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function inbox -Object_Type HABinbox
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABlinks

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function links -Object_Type HABlinks
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABthings

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function things -Object_Type HABthings
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABsitemaps

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function sitemaps -Object_Type HABsitemaps
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABiconsets

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function iconsets -Object_Type HABiconsets
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABextensions

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function extensions -Object_Type HABextensions
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habmincharts

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/charts -Object_Type habmincharts
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habmindashboards

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/dashboards -Object_Type habmindashboards
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habmindesigner

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/designer -Object_Type habmindesigner
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habminfloorplan

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/floorplan -Object_Type habminfloorplan
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-habminrules

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function habmin/rules -Object_Type habminrules
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABtemplates

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function templates -Object_Type HABtemplates
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABmodule_types

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function module-types -Object_Type HABmodule_types
    $MySelf
    }


# autogenerated from @sddc_guy codegen
    

Function Get-HABrules

    {
    $My_Method = 'GET'
    Invoke-OpenHABREST -Method $My_Method -Function rules -Object_Type HABrules
    $MySelf
    }

